// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ALBClient is the client API for ALB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ALBClient interface {
	// If the requested service is any status but SERVING, the call will fail
	// with status UNAVAILABLE.
	Healthcheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aLBClient struct {
	cc grpc.ClientConnInterface
}

func NewALBClient(cc grpc.ClientConnInterface) ALBClient {
	return &aLBClient{cc}
}

func (c *aLBClient) Healthcheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/AWS.ALB/healthcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ALBServer is the server API for ALB service.
// All implementations must embed UnimplementedALBServer
// for forward compatibility
type ALBServer interface {
	// If the requested service is any status but SERVING, the call will fail
	// with status UNAVAILABLE.
	Healthcheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedALBServer()
}

// UnimplementedALBServer must be embedded to have forward compatible implementations.
type UnimplementedALBServer struct {
}

func (UnimplementedALBServer) Healthcheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedALBServer) mustEmbedUnimplementedALBServer() {}

// UnsafeALBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ALBServer will
// result in compilation errors.
type UnsafeALBServer interface {
	mustEmbedUnimplementedALBServer()
}

func RegisterALBServer(s grpc.ServiceRegistrar, srv ALBServer) {
	s.RegisterService(&ALB_ServiceDesc, srv)
}

func _ALB_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ALBServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AWS.ALB/healthcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ALBServer).Healthcheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ALB_ServiceDesc is the grpc.ServiceDesc for ALB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ALB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AWS.ALB",
	HandlerType: (*ALBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "healthcheck",
			Handler:    _ALB_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alb.proto",
}
